version: "3.9"

services:
  backend:
    image: ghcr.io/darktezi/website-backend:latest
    container_name: website_backend
    ports:
      - "127.0.0.1:8180:8080"
    volumes:
      - backend_data:/app
    networks:
      - webnet
    restart: unless-stopped

  frontend:
    image: nginx:latest
    container_name: website_frontend
    ports:
      - "127.0.0.1:8181:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./assets:/usr/share/nginx/html/assets
      - ./images:/usr/share/nginx/html/images
      - ./error:/usr/share/nginx/html/error
    networks:
      - webnet
    restart: unless-stopped

volumes:
  backend_data:
networks:
  webnet:
